title = "Shane Lee"
baseURL = "https://shanelee.name"
languageCode = "en-us"
theme = "ananke"
# themesDir = "../.."
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
# Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[[menu.main]]
name = "Blog"
weight = 0
identifier = "Blog"
url = "https://blog.shanelee.name"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "I am a Development lead in Melbourne, Australia. Read my blog."
  facebook = ""
  twitter = "https://twitter.com/shavo27"
  instagram = ""
  youtube = ""
  github = "https://github.com/shavo007"
  gitlab = ""
  linkedin = "https://au.linkedin.com/in/shane-lee-69114326"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2

# [params.adsense]
# client = "ca-pub-12345"
# inArticleSlot = "12345"
